Lesson8/college/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path

from teachers import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('admin/', admin.site.urls),
    path('groups/', include('groups.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    re_path(r'^silk/', include('silk.urls', namespace='silk')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

Lesson8/groups/urls.py
from django.urls import path

from groups import views

app_name = "groups"

urlpatterns = [
    path('create/', views.create, name='create'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('show/', views.show, name='show'),
]

Lesson8/groups/models.py
from django.db import models

from students.models import Student

from teachers.models import Teacher


class Group(models.Model):
    group_name = models.CharField(max_length=32)
    department = models.CharField(max_length=32)
    number_of_students = models.PositiveSmallIntegerField()
    curator = models.ForeignKey(Teacher, on_delete=models.SET_NULL, null=True)
    headman = models.OneToOneField(Student, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.group_name} / {self.department}'

    @property
    def info(self) -> str:
        return f'{self.id} | {self.group_name} | {self.department} | ' \
               f'{str(self.curator)} | {self.headman} | {self.number_of_students}'

Lesson8/groups/forms.py
from django import forms

from groups.models import Group


class CreateGroupForm(forms.ModelForm):

    class Meta:
        model = Group
        fields = ('group_name', 'department', 'curator', 'headman', 'number_of_students')

Lesson8/groups/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from groups.forms import CreateGroupForm
from groups.models import Group


def create(request):
    if request.method == 'POST':
        form = CreateGroupForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('groups:show'))
    else:
        form = CreateGroupForm()
    context = {
        'create_form': form,
        'action': 'Create group',
    }
    return render(request, 'group-create-edit.html', context=context)


def edit(request, pk):
    group = get_object_or_404(Group, id=pk)
    if request.method == 'POST':
        form = CreateGroupForm(request.POST, instance=group)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('students:show'))
    else:
        form = CreateGroupForm(instance=group)
    context = {
        'create_form': form,
        'action': 'Edit group',
        'id': pk,
    }
    return render(request, 'group-create-edit.html', context=context)


def delete(request, pk):
    group = get_object_or_404(Group, id=pk)
    group.delete()
    return HttpResponseRedirect(reverse('groups:show'))


def show(request):
    params = ['group_name', 'department', 'number_of_students']
    groups = Group.objects.all().select_related('headman', 'curator')
    for param in params:
        value = request.GET.get(param)
        if value:
            groups = groups.filter(**{param: value})
    context = {'groups': groups}
    return render(request, 'groups-show.html', context=context)

Lesson8/groups/templates/group-create-edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ action }}</title>
</head>
<body>

<a href="{% url 'index' %}">Main page</a> <a href="{% url 'groups:show' %}">Show groups</a><br><br>
<b>{{ action }}</b>
<form method="post">
    {% csrf_token %}
    {{ create_form.as_p }}
    <button type="submit">{{ action }}</button>
</form>
{% if id %}
    <form action="{% url 'groups:delete' id %}">
        <input type="submit" value="Delete" />
    </form>
{% endif %}

</body>
</html>

Lesson8/groups/templates/groups-show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Groups list</title>
</head>
<body>

<a href="{% url 'index' %}">Main page</a> <a href="{% url 'groups:create' %}">Create group</a><br><br>
{% if groups %}
    <table bordercolor="black" border="1" cellpadding="3" cellspacing="0">
        <caption><b>Groups list:</b></caption>
            <tr>
                <th>ID</th>
                <th>Group Name</th>
                <th>Department</th>
                <th>Number of Students</th>
                <th>Curator</th>
                <th>Headman</th>
                <th>Edit</th>
            </tr>
    {% for group in groups %}
            <tr>
                <td>{{ group.id }}</td>
                <td>{{ group.group_name }}</td>
                <td>{{ group.department }}</td>
                <td>{{ group.number_of_students }}</td>
                <td>{{ group.curator }}</td>
                <td>{{ group.headman }}</td>
                <td>
                    <form action="{% url 'groups:edit' group.id %}">
                    <input type="submit" value="Edit" />
                    </form>
                </td>
            </tr>
    {% endfor %}
    </table>
{% else %}
    Groups list is empty.
{% endif %}

</body>
</html>