Lesson8/college/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path

from teachers import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('admin/', admin.site.urls),
    path('groups/', include('groups.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    re_path(r'^silk/', include('silk.urls', namespace='silk')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

Lesson8/groups/urls.py
from django.urls import path

from groups import views

app_name = "groups"

urlpatterns = [
    path('create/', views.create, name='create'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('show/', views.show, name='show'),
]

Lesson8/students/urls.py
from django.urls import path

from students import views

app_name = "students"

urlpatterns = [
    path('create/', views.create, name='create'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('show/', views.show, name='show'),
]

Lesson8/teachers/urls.py
from django.urls import path

from teachers import views

app_name = "teachers"

urlpatterns = [
    path('create/', views.create, name='create'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('show/', views.show, name='show'),
]

Lesson8/teachers/models.py
from django.db import models


class Teacher(models.Model):
    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=32)
    age = models.PositiveSmallIntegerField()
    teaching_subjects = models.CharField(max_length=32)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    @property
    def info(self) -> str:
        return f'{self.id} | {self.first_name} {self.last_name} | {str(self.age)} | {self.teaching_subjects}'


class Logger(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    method = models.CharField(max_length=16)
    path = models.CharField(max_length=64)
    execution_time = models.FloatField()

    @property
    def info(self) -> str:
        return f'{self.id} {self.created} {self.method} {self.path} {str(self.execution_time)}'

Lesson8/teachers/forms.py
from django import forms

from teachers.models import Teacher


class CreateTeacherForm(forms.ModelForm):

    class Meta:
        model = Teacher
        fields = ('first_name', 'last_name', 'age', 'teaching_subjects')


class ContactUSForm(forms.Form):
    email_from = forms.EmailField(label='From (e-mail)')
    title = forms.CharField(label='Title', max_length=100)
    message = forms.CharField(label='Message', max_length=1000, widget=forms.Textarea)

Lesson8/teachers/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from teachers.forms import ContactUSForm, CreateTeacherForm
from teachers.models import Teacher
from teachers.tasks import send_message


def create(request):
    if request.method == 'POST':
        form = CreateTeacherForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('teachers:show'))
    else:
        form = CreateTeacherForm()
    context = {
        'create_form': form,
        'action': 'Create teacher',
    }
    return render(request, 'teacher-create-edit.html', context=context)


def edit(request, pk):
    teacher = get_object_or_404(Teacher, id=pk)
    if request.method == 'POST':
        form = CreateTeacherForm(request.POST, instance=teacher)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('teachers:show'))
    else:
        form = CreateTeacherForm(instance=teacher)
    context = {
        'create_form': form,
        'action': 'Edit teacher',
        'id': pk,
    }
    return render(request, 'teacher-create-edit.html', context=context)


def delete(request, pk):
    teacher = get_object_or_404(Teacher, id=pk)
    teacher.delete()
    return HttpResponseRedirect(reverse('teachers:show'))


def show(request):
    params = ['first_name', 'last_name', 'age', 'teaching_subjects']
    teachers = Teacher.objects.all()
    for param in params:
        value = request.GET.get(param)
        if value:
            teachers = teachers.filter(**{param: value})
    context = {'teachers': teachers}
    return render(request, 'teachers-show.html', context=context)


def index(request):
    return render(request, 'index.html')


def contact(request):
    if request.method == 'POST':
        form = ContactUSForm(request.POST)
        if form.is_valid():
            email_from = request.POST.get('email_from')
            title = request.POST.get('title')
            message = request.POST.get('message')
            send_message.delay(email_from, title, message)
            return render(request, 'contact-success.html')
    else:
        form = ContactUSForm()
    context = {
        'create_form': form,
        'action': 'Contact Us',
    }
    return render(request, 'contact.html', context=context)

Lesson8/teachers/templates/contact-success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Success!</title>
</head>
<body>

<a href="{% url 'index' %}">Main page</a><br><br>
<b>Thank you! Your message has been sent successfully.</b><br><br>
<i>You will be automatically redirected to the main page.</i>
<meta http-equiv="refresh" content="5;url={% url 'index' %}" />


</body>
</html>

Lesson8/teachers/templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ action }}</title>
</head>
<body>

<a href="{% url 'index' %}">Main page</a><br><br>
<b>{{ action }}</b>
<form method="post">
    {% csrf_token %}
    {{ create_form.as_p }}
    <button type="submit">{{ action }}</button>
</form>

</body>
</html>

Lesson8/teachers/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Main page</title>
</head>
<body>

<a href="{% url 'teachers:create' %}">Create teacher</a><br>
<a href="{% url 'teachers:show' %}">Show teachers</a><br><br>
<a href="{% url 'students:create' %}">Create student</a><br>
<a href="{% url 'students:show' %}">Show students</a><br><br>
<a href="{% url 'groups:create' %}">Create group</a><br>
<a href="{% url 'groups:show' %}">Show groups</a><br><br>
<a href="{% url 'contact' %}">Contact Us</a>

</body>
</html>

Lesson8/teachers/templates/teacher-create-edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ action }}</title>
</head>
<body>

<a href="{% url 'index' %}">Main page</a> <a href="{% url 'teachers:show' %}">Show teachers</a><br><br>
<b>{{ action }}</b>
<form method="post">
    {% csrf_token %}
    {{ create_form.as_p }}
    <button type="submit">{{ action }}</button>
</form>
{% if id %}
    <form action="{% url 'teachers:delete' id %}">
        <input type="submit" value="Delete" />
    </form>
{% endif %}

</body>
</html>

Lesson8/teachers/templates/teachers-show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teachers list</title>
</head>
<body>

<a href="{% url 'index' %}">Main page</a> <a href="{% url 'teachers:create' %}">Create teacher</a><br><br>
{% if teachers %}
    <table bordercolor="black" border="1" cellpadding="3" cellspacing="0">
        <caption><b>Teachers list:</b></caption>
            <tr>
                <th>ID</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Age</th>
                <th>Teaching Subjects</th>
                <th>Edit</th>
            </tr>
    {% for teacher in teachers %}
            <tr>
                <td>{{ teacher.id }}</td>
                <td>{{ teacher.first_name }}</td>
                <td>{{ teacher.last_name }}</td>
                <td>{{ teacher.age }}</td>
                <td>{{ teacher.teaching_subjects }}</td>
                <td>
                    <form action="{% url 'teachers:edit' teacher.id %}">
                    <input type="submit" value="Edit" />
                    </form>
                </td>
            </tr>
    {% endfor %}
    </table>
{% else %}
    Teachers list is empty.
{% endif %}

</body>
</html>