Lesson8/college/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path

from teachers import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('admin/', admin.site.urls),
    path('groups/', include('groups.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    re_path(r'^silk/', include('silk.urls', namespace='silk')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

Lesson8/groups/urls.py
from django.urls import path

from groups import views

app_name = "groups"

urlpatterns = [
    path('create/', views.create, name='create'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('show/', views.show, name='show'),
]

Lesson8/students/urls.py
from django.urls import path

from students import views

app_name = "students"

urlpatterns = [
    path('create/', views.create, name='create'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('show/', views.show, name='show'),
]

Lesson8/students/models.py
from django.db import models


class Student(models.Model):
    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=32)
    age = models.PositiveSmallIntegerField()
    phone = models.CharField(max_length=16, default='')

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    @property
    def info(self) -> str:
        return f'{self.id} | {self.first_name} {self.last_name} | {str(self.age)} | {self.phone}'

Lesson8/students/forms.py
from django import forms

from students.models import Student


class CreateStudentForm(forms.ModelForm):

    class Meta:
        model = Student
        fields = ('first_name', 'last_name', 'age', 'phone')

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if not phone.isdigit():
            raise forms.ValidationError("The phone must be a number!")
        return phone

Lesson8/students/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from students.forms import CreateStudentForm
from students.models import Student


def create(request):
    if request.method == 'POST':
        form = CreateStudentForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('students:show'))
    else:
        form = CreateStudentForm()
    context = {
        'create_form': form,
        'action': 'Create student',
    }
    return render(request, 'student-create-edit.html', context=context)


def edit(request, pk):
    student = get_object_or_404(Student, id=pk)
    if request.method == 'POST':
        form = CreateStudentForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('students:show'))
    else:
        form = CreateStudentForm(instance=student)
    context = {
        'create_form': form,
        'action': 'Edit student',
        'id': pk,
    }
    return render(request, 'student-create-edit.html', context=context)


def delete(request, pk):
    student = get_object_or_404(Student, id=pk)
    student.delete()
    return HttpResponseRedirect(reverse('students:show'))


def show(request):
    params = ['age', 'first_name', 'last_name']
    students = Student.objects.all()
    for param in params:
        value = request.GET.get(param)
        if value:
            students = students.filter(**{param: value})
    context = {'students': students}
    return render(request, 'students-show.html', context=context)

Lesson8/students/templates/student-create-edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ action }}</title>
</head>
<body>

<a href="{% url 'index' %}">Main page</a> <a href="{% url 'students:show' %}">Show students</a><br><br>
<b>{{ action }}</b>
<form method="post">
    {% csrf_token %}
    {{ create_form.as_p }}
    <button type="submit">{{ action }}</button>
</form>
{% if id %}
    <form action="{% url 'students:delete' id %}">
        <input type="submit" value="Delete" />
    </form>
{% endif %}

</body>
</html>

Lesson8/students/templates/students-show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Students list</title>
</head>
<body>

<a href="{% url 'index' %}">Main page</a> <a href="{% url 'students:create' %}">Create student</a><br><br>
{% if students %}
    <table bordercolor="black" border="1" cellpadding="3" cellspacing="0">
        <caption><b>Students list:</b></caption>
            <tr>
                <th>ID</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Age</th>
                <th>Phone</th>
                <th>Edit</th>
            </tr>
    {% for student in students %}
            <tr>
                <td>{{ student.id }}</td>
                <td>{{ student.first_name }}</td>
                <td>{{ student.last_name }}</td>
                <td>{{ student.age }}</td>
                <td>{{ student.phone }}</td>
                <td>
                    <form action="{% url 'students:edit' student.id %}">
                    <input type="submit" value="Edit" />
                    </form>
                </td>
            </tr>
    {% endfor %}
    </table>
{% else %}
    Students list is empty.
{% endif %}

</body>
</html>